language: go

sudo: false

go:
  - 1.14.x
  - 1.15.x
  - 1.16.x

env:
  - GO111MODULE=on

install:
  - cd cmd/logAgent && go build && cd -
  - cd cmd/logTransfer && go build && cd -
  - cd cmd/logManager && go build && cd -

script:
  - cd cmd/logAgent && go test -v ./... && cd -
  - cd cmd/logTransfer && go test -v ./... && cd -
  - cd cmd/logManager && go test -v ./... && cd -
